### PR TITLE
Improvement/#40

### PR DESCRIPTION
**Pull request by GalochkinKirov**

### CODE REVIEW

**Comment by OAGr** [comment]
Good work with this.
Some other things I think should be part of this:
- The new state should be accessible on query requests of measurables.
- The old state (the one that was a string, straight from the database) should not be accessible via the api.

**Comment by GalochkinKirov** [comment]
> Good work with this.
> Some other things I think should be part of this:
> 
> * The new state should be accessible on query requests of measurables.
> * The old state (the one that was a string, straight from the database) should not be accessible via the api.

It is not a New State attribute, it is the representation of state string. State string is the same, but there is new possible value "JUDGEMENT_PENDING". This is why "state" accessible, but number representation of state no.

Or I missed something in your questions.

**Comment by OAGr** [comment]
Hm... I'll try it out and see what you mean.

**Comment by OAGr** [comment]
Yea; right now ``state`` on ``measurable`` returns a string!. It should instead return a ``measurableState!``

**Comment by GalochkinKirov** [comment]
Ok, got it. Going to fix.

**Pull request merged**
